# Generated by Django 4.2 on 2023-05-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracker", "0002_expense_currency_alter_expense_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("C", "Credit"),
                    ("D", "Debit"),
                    ("T", "Transfer"),
                    ("R", "Refund"),
                ],
                default="D",
                max_length=1,
            ),
        ),
    ]
