# Generated by Django 4.2 on 2023-05-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracker", "0005_investmentcategories_investment_investment_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InvestmentCategories",
            new_name="InvestmentCategory",
        ),
    ]
